export const langArg = {
  C: 'C',
  'C++': 'CPP',
  'C++11': 'CPP11',
  'C++14': 'CPP14',
  Clojure: 'CLOJURE',
  'C#': 'CSHARP',
  Go: 'GO',
  Haskell: 'HASKELL',
  Java: 'JAVA',
  'Java 8': 'JAVA8',
  'JavaScript(Rhino)': 'JAVASCRIPT',
  'JavaScript(Nodejs)': 'JAVASCRIPT_NODE',
  Kotlin: 'KOTLIN',
  'Objective C': 'OBJECTIVEC',
  Pascal: 'PASCAL',
  Perl: 'PERL',
  PHP: 'PHP',
  'Python 2': 'PYTHON',
  'Python 3': 'PYTHON3',
  R: 'R',
  Ruby: 'RUBY',
  Rust: 'RUST',
  Scala: 'SCALA',
  Swift: 'SWIFT',
  'Swift 4.1': 'SWIFT_4_1',
};
